workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Build Android APK
        script: |
          # 1. Setup environnement
          NODE_DIR=$(dirname $(which node))
          export PATH="$NODE_DIR:$PATH"
          
          # 2. Création des dossiers nécessaires
          mkdir -p android/app/src/main/assets
          
          # 3. Génération MANUELLE du bundle (On le fait nous-même proprement)
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res \
            --reset-cache

          # 4. Compilation APK en neutralisant la commande interne qui crash
          cd android
          chmod +x gradlew
          # On remplace la commande bundle par un simple "echo" pour que Gradle ne puisse pas échouer
          ./gradlew assembleRelease \
            -PreactNativeBundleCommand="echo skipping bundle" \
            -PreactNativeNodeExecutableAndArgs="$NODE_DIR/node" \
            --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
