workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          # Nettoyage radical du cache NPM et des modules
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
      - name: Build Android APK
        script: |
          NODE_DIR=$(dirname $(which node))
          export PATH="$NODE_DIR:$PATH"
          
          mkdir -p android/app/src/main/assets
          
          cd android
          chmod +x gradlew
          # On laisse Gradle faire son travail normalement car Babel est maintenant verrouillé
          ./gradlew assembleRelease \
            -PreactNativeNodeExecutableAndArgs="$NODE_DIR/node" \
            --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
