workflows:
  android-workflow:
    name: Android Build
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Force Build APK
        script: |
          # 1. Créer le dossier pour le code
          mkdir -p android/app/src/main/assets
          
          # 2. Générer le code manuellement (Bypass Babel/Gradle conflict)
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          
          # 3. Compiler l'APK en disant à Gradle d'ignorer le JS
          cd android
          ./gradlew assembleRelease -PbundleInRelease=false --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
