workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Build Android APK
        script: |
          # 1. Setup Node
          NODE_DIR=$(dirname $(which node))
          export PATH="$NODE_DIR:$PATH"
          
          # 2. Création des dossiers d'assets
          mkdir -p android/app/src/main/assets
          
          # 3. Génération manuelle du bundle (On s'assure que le JS est prêt)
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res \
            --reset-cache

          # 4. Compilation de l'APK en ignorant la tâche automatique qui crashait
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease -x :app:bundleReleaseJsAndAssets \
            -PreactNativeNodeExecutableAndArgs="$NODE_DIR/node" \
            --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - ton-email@exemple.com
